import { z } from 'zod';
import { anthropic, MODELS, callCostCents } from '../client';
import { trackAgentCall } from '@/lib/billing/track-usage';
import { stripFences } from '../lib/strip-fences';

const Schema = z.object({
  /** 0 = clearly human, 1 = clearly AI */
  score: z.number().min(0).max(1),
  verdict: z.enum(['human', 'mixed', 'likely_ai']),
  reasoning: z.string(),
  tells: z.array(z.string()).max(6),
});

export type AiCheckResult = z.infer<typeof Schema>;

const SYSTEM = `You audit a piece of prose to estimate whether it was written by a human or generated by an LLM.

Use these signals:
- Sentence rhythm variance (humans vary; LLMs trend uniform)
- Unusual word choices, idiosyncratic phrasing, voice
- Concrete specifics + lived detail vs. plausible-but-generic
- Hedging patterns ('it's important to note', 'in conclusion', list-of-three)
- Awkward transitions, abrupt shifts of register, real friction
- Formatting tics (em-dashes, parallel structures, bullet-y prose)

Output JSON ONLY:
{
  "score": 0.0-1.0,
  "verdict": "human" | "mixed" | "likely_ai",
  "reasoning": "<one sentence>",
  "tells": ["<concrete signal you saw>", ...]
}

Be honest. A score around 0.5 is fine if it's genuinely ambiguous.`;

export async function checkIfAiGenerated({
  text,
  orgId,
}: {
  text: string;
  orgId: string;
}): Promise<AiCheckResult> {
  const resp = await anthropic.messages.create({
    model: MODELS.REASONING,
    max_tokens: 800,
    system: [{ type: 'text', text: SYSTEM, cache_control: { type: 'ephemeral' } }],
    messages: [{ role: 'user', content: text.slice(0, 12000) }],
  });

  const costCents = callCostCents({
    model: MODELS.REASONING,
    inputTokens: resp.usage.input_tokens,
    outputTokens: resp.usage.output_tokens,
    cacheReadTokens: resp.usage.cache_read_input_tokens ?? 0,
  });
  await trackAgentCall({ orgId, meter: 'gap', amount: 1, costCents });

  const block = resp.content[0];
  const raw = block && block.type === 'text' ? block.text : '';
  const jsonText = stripFences(raw);
  return Schema.parse(JSON.parse(jsonText));
}
